// Jira integration types.
// These mirror the types generated by jira-client crate.
// Once `pnpm run remote:generate-types` is run with the remote crate,
// these should be replaced with imports from 'shared/remote-types'.

export interface JiraProject {
  id: string;
  key: string;
  name: string;
  projectTypeKey?: string | null;
}

export interface JiraIssue {
  id: string;
  key: string;
  self: string;
  fields: JiraIssueFields;
}

export interface JiraIssueFields {
  summary: string;
  description: unknown | null;
  status: JiraStatus | null;
  priority: JiraPriority | null;
  issuetype: JiraIssueType | null;
  assignee: JiraUser | null;
  reporter: JiraUser | null;
  created: string | null;
  updated: string | null;
  labels: string[];
}

export interface JiraStatus {
  id: string;
  name: string;
  statusCategory: JiraStatusCategory | null;
}

export interface JiraStatusCategory {
  id: number;
  key: string;
  name: string;
}

export interface JiraPriority {
  id: string;
  name: string;
}

export interface JiraIssueType {
  id: string;
  name: string;
  subtask: boolean;
}

export interface JiraUser {
  accountId: string;
  displayName: string;
}

export interface JiraTransition {
  id: string;
  name: string;
  to: JiraStatus;
}

export interface JiraSearchResult {
  startAt?: number | null;
  maxResults?: number | null;
  total?: number | null;
  issues: JiraIssue[];
  isLast?: boolean | null;
}

export interface JiraConnectRequest {
  site_url: string;
  auth: JiraAuthPayload;
}

export type JiraAuthPayload =
  | { type: 'oauth2'; code: string; redirect_uri: string }
  | { type: 'api_token'; email: string; token: string };

export interface JiraImportRequest {
  project_id: string;
  status_id: string;
  issue_keys: string[];
}

export interface JiraConnectionInfo {
  connected: boolean;
  site_url: string | null;
  auth_type: string | null;
  connected_at: string | null;
}

export interface JiraSearchRequest {
  query: string;
  project_key?: string | null;
  max_results?: number | null;
}

export interface JiraOAuthAuthorizeResponse {
  authorize_url: string;
}

export interface AtlassianSite {
  id: string;
  url: string;
  name: string;
}

export interface JiraCommentView {
  id: string;
  author_name: string;
  body_markdown: string;
  created: string | null;
}

export interface JiraStatusMapping {
  vk_status_name: string;
  jira_category_key: string;
}

export interface JiraStatusMappingRequest {
  vk_status_name: string;
  jira_category_key: string;
}

export interface JiraStatusMappingDeleteRequest {
  vk_status_name: string;
}

export interface JiraStatusView {
  name: string;
  category_key: string;
  category_name: string;
}

/** Shape of the `jira` field inside `extension_metadata` on imported issues. */
export interface JiraExtensionMetadata {
  issue_key: string;
  issue_id: string;
  issue_url: string;
  jira_project_key: string;
  jira_status: string | null;
  imported_at: string;
  last_synced_at?: string | null;
}
